### ISSUE TITLE
Hit count is not persistent when loading a save

### ISSUE THREAD

**Issue by derekhansell** [Dastan21/HollowKnight.HitCounter#1]
Hey there! The mod doesn't keep track of my hits when I exit the game and reload. I'm on the Voidheart edition on Game Pass. Not sure what logs you would need.

**Comment by Dastan21** [comment]
1. How do you quit? Alt+F4 ? Quit to menu ?
2. Check if there are any file named `HitCounter.GlobalSettings` under `%AppData%\..\Local\Packages\[...]\`

You can also share your `ModLog.txt` and `HitCounter.GlobalSettings` here if you have them.

**Comment by derekhansell** [comment]
FYI, I switched to the Steam version of Hollow Knight and I'm having the same problem. I've attached everything I can find related to the mod and my play session. I quit to menu and then exit the game. You can see my progress in this video (starts near the end of my stream).

https://www.youtube.com/live/9CnKpQDCUZU?si=qR0DT01juFNFGqCa&t=6057

[HitCounterLogs.zip](https://github.com/Dastan21/HollowKnight.HitCounter/files/14155257/HitCounterLogs.zip)
[HitCounterFolder.zip](https://github.com/Dastan21/HollowKnight.HitCounter/files/14155254/HitCounterFolder.zip)

**Comment by derekhansell** [comment]
It's like the mod is failing to write a file somewhere - where are the hits and PB values supposed to be tracked?

**Comment by derekhansell** [comment]
I fully deleted the Team Cherry folder from %userprofile%\AppData\LocalLow, uninstalled Hollow Knight, both from Steam and the Xbox App, purged the install folders in both locations to remove all trace of the mod, and reset Lumafly, and the mod still doesn't keep hits through a reset after a fresh install. What other info can I provide you?

HK and Steam are installed on D, %userprofile% is on C. I'm on Windows 11. The DeathCounter hit mod _does_ track total hits through a quit and save load.

Should I try not using a mod installer to load the mod?

**Comment by derekhansell** [comment]
Should I try _not_ using a mod installer to load the mod?

**Comment by Dastan21** [comment]
It saves the latest completed run (if it has less or equal hits).
Completing a run means you have to go to the last split and press the "next split" keybind.
Let me know if you have any idea.

**Comment by derekhansell** [comment]
Oh, OK! Yeah, totally wasn't understood that's how the mod locks in a value. Is there any way to make it lock in current data when you quit to menu? Failing that, is there a way to edit the `HitCounter.GlobalSettings` file so I can keep track of the values myself and track my progress? The values seem to reset to defaults if I try to manually update them. I rarely have time to finish a run in one sitting.

**Comment by Dastan21** [comment]
Values or loaded in memory when you launch the game, so it overrides them when you edit the file while the game is open.
I can make a menu ingame to edit hits. I will work in it in the few days.

**Comment by derekhansell** [comment]
You are a hero, sir! There's absolutely no rush. Thank you so much!

**Comment by Dastan21** [comment]
Hey, so I have added keybinds to add/remove hits in the current session. You can update PBs by doing "next split" until the end (before it was checking if the total hits was lower than the current PBs). And finally the session hits are now saved and loaded.
You can update the mod from Scarab/Lumafly.
Thanks for using the mod, and good luck for your runs :)
